### ISSUE TITLE
Installed via HACS but integration not showing

### ISSUE THREAD

**Issue by borpin** [iprak/weatherapi#4]
Hi, I have installed this via HACS, but the integration is not showing. The button on your Readme isn't working either.

Can't see a thread on the forum to use.

**Comment by iprak** [comment]
Is the integration not appearing in the available integrations list?

That button itself doesn't add the integration but such a button shown be in your HomeAssistant's Integration page.

**Comment by borpin** [comment]
All I see, is this if I search for Weather

![image](https://user-images.githubusercontent.com/1322749/141165779-a463c7a6-5129-42cf-9154-110aaa28b040.png)

Yes I realise the button doesn't but it takes me to a 404 page (2 different issues really).

**Comment by borpin** [comment]
Ah, a second restart seems to have solved it.

![image](https://user-images.githubusercontent.com/1322749/141166227-30712efd-1795-4732-abaa-82dbe60fec7b.png)

**Comment by iprak** [comment]
I don't think another restart should have been necessary. I looked around in HACS issues list but did not see anything. But I am glad that the issue has been resolved.

**Comment by hw-monkey** [comment]
Encountered the same problem. Did a second restart. Then a third. problem still occurred. Although I clicked all through home asssistant, something was still cachced. When I forced the browser to refresh the list of integrations by holding shift while pressing refresh on the Integrations page, the WeatherAPI finally became available. 

Hope this helps someone
